name: LCXX build - Mac

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-linux:
    runs-on: mac-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      working-directory: build
      run: cmake --build . 

    - uses: actions/upload-artifact@master
      with:
        name: lcxx-tests-mac
        path: |
          ${{ github.workspace }}/build/tests/*/
        retention-days: 3
        if-no-files-found: error
