name: LCXX build & test - Ubuntu

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

defaults:
  run:
    shell: bash

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.1
      id: install-boost
      with:
          boost_version: 1.78.0
          platform_version: 20.04

    - name: Get latest GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64

    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B build

    - name: build
      run: cmake --build build

    - uses: actions/upload-artifact@master
      with:
        name: lcxx-tests-ubuntu
        path: |
          ${{ github.workspace }}/build/tests/*/
        retention-days: 3
        if-no-files-found: error


  tests-linux:
    needs: build-linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get latest GCC (libstdc++ required)
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64

    - uses: actions/download-artifact@v3
      with:
        name: lcxx-tests-ubuntu

    - name: display artifacts
      run: ls -R

    - name: crypto-tests
      run: chmod +x crypto/crypto_test && ./crypto/crypto_test

    - name: identifiers-tests
      run: chmod +x identifiers/identifiers_test && ./identifiers/identifiers_test

    - name: lcxx-tests
      run: chmod +x lcxx/lcxx_test && ./lcxx/lcxx_test