name: LCXX build & test - Windows

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

defaults:
  run:
    shell: bash

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: install OpenSSL
      run: choco install openssl

    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..

    - name: build
      working-directory: build
      run: cmake --build . 

    - uses: actions/upload-artifact@master
      with:
        name: lcxx-tests-windows
        path: |
          ${{ github.workspace }}/build/tests/*/
        retention-days: 3
        if-no-files-found: error

  tests-windows:
    needs: build-windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: install OpenSSL
      run: choco install openssl

    - uses: actions/download-artifact@v3
      with:
        name: lcxx-tests-windows

    - name: display artifacts
      run: ls -R

    - name: crypto-tests
      run: |
      ls -lR build
      ./crypto/crypto_test.exe

    - name: identifiers-tests
      run: ./identifiers/identifiers_test.exe

    - name: lcxx-tests
      run: ./lcxx/lcxx_test.exe