name: LCXX build & test - Mac

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

defaults:
  run:
    shell: bash

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: build
      working-directory: build
      run: cmake --build . 

    - name: list artifacts
      run: ls -R

    - uses: actions/upload-artifact@master
      with:
        name: lcxx-tests-mac
        path: |
          ${{ github.workspace }}/build/tests/*/
        retention-days: 3
        if-no-files-found: error

  tests-mac:
    needs: build-mac
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: lcxx-tests-mac

    - name: display artifacts
      run: ls -R

    - name: crypto-tests
      run: chmod +x crypto/crypto_test && ./crypto/crypto_test

    # - name: identifiers-tests
    #   run: chmod +x identifiers/identifiers_test && ./identifiers/identifiers_test

    - name: lcxx-tests
      run: chmod +x lcxx/lcxx_test && ./lcxx/lcxx_test