name: LCXX generate docs

on:
  push:
    tags:
      - v*.*.*

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen

    - name: build doxygen
      working-directory: docs/Doxygen
      run: doxygen Doxyfile-prj.cfg

    - name: get sphinx + deps
      run: pip install sphinx breathe exhale git+https://github.com/bashtage/sphinx-material.git

    - name: build sphinx docs
      working-directory: docs/Sphinx
      run: make html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/Sphinx/build/html

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1